apiVersion: apps/v1
kind: Deployment
metadata:
  name: veritrustai
  labels:
    app: veritrustai
spec:
  replicas: 3
  selector:
    matchLabels:
      app: veritrustai
  template:
    metadata:
      labels:
        app: veritrustai
    spec:
      containers:
      - name: veritrustai
        image: veritrustai:latest
        ports:
        - containerPort: 5000
        env:
        - name: FLASK_APP
          value: "app"
        - name: FLASK_ENV
          value: "production"
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: veritrustai-secrets
              key: mongodb-uri
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: veritrustai-secrets
              key: aws-access-key
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: veritrustai-secrets
              key: aws-secret-key
        - name: JWT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: veritrustai-secrets
              key: jwt-secret
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 15
          periodSeconds: 20
        volumeMounts:
        - name: logs
          mountPath: /app/logs
      volumes:
      - name: logs
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: veritrustai
spec:
  selector:
    app: veritrustai
  ports:
  - port: 80
    targetPort: 5000
  type: LoadBalancer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: veritrustai
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - host: api.veritrustai.com
    http:
      paths:
      - path: /api(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: veritrustai
            port:
              number: 80 